# Generated by Django 4.1.1 on 2022-09-08 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('event_type', models.CharField(choices=[('A', 'Appeared'), ('D', 'Disappeared')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Trackable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TrackableClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Tracklet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appeared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appear_event', to='timeline.event')),
                ('disappeared', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.event')),
                ('instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.trackable')),
            ],
        ),
        migrations.AddField(
            model_name='trackable',
            name='object_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.trackableclass'),
        ),
        migrations.AddField(
            model_name='event',
            name='instance',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='timeline.trackable'),
        ),
    ]
