# Generated by Django 4.1.1 on 2022-09-08 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='instance',
            new_name='trackable',
        ),
        migrations.RenameField(
            model_name='tracklet',
            old_name='instance',
            new_name='trackable',
        ),
    ]
