# Generated by Django 4.1.1 on 2022-09-08 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0002_rename_instance_event_trackable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackableclass',
            name='class_id',
            field=models.PositiveSmallIntegerField(default=0),
            preserve_default=False,
        ),
    ]
