# Generated by Django 4.1.1 on 2022-09-08 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0005_event_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='image_path',
            field=models.CharField(default='timeline/images/placeholder.png', max_length=200),
        ),
    ]
