# Generated by Django 4.1.1 on 2022-09-12 15:23

from django.db import models, migrations


DEFAULT_TRACKABLE_CLASSES = (
    "person",
    "bicycle",
    "car",
    "motorcycle",
    "airplane",
    "bus",
    "train",
    "truck",
    "boat",
    "traffic light",
    "fire hydrant",
    "stop sign",
    "parking meter",
    "bench",
    "bird",
    "cat",
    "dog",
    "horse",
    "sheep",
    "cow",
    "elephant",
    "bear",
    "zebra",
    "giraffe",
    "backpack",
    "umbrella",
    "handbag",
    "tie",
    "suitcase",
    "frisbee",
    "skis",
    "snowboard",
    "sports ball",
    "kite",
    "baseball bat",
    "baseball glove",
    "skateboard",
    "surfboard",
    "tennis racket",
    "bottle",
    "wine glass",
    "cup",
    "fork",
    "knife",
    "spoon",
    "bowl",
    "banana",
    "apple",
    "sandwich",
    "orange",
    "broccoli",
    "carrot",
    "hot dog",
    "pizza",
    "donut",
    "cake",
    "chair",
    "couch",
    "potted plant",
    "bed",
    "dining table",
    "toilet",
    "tv",
    "laptop",
    "mouse",
    "remote",
    "keyboard",
    "cell phone",
    "microwave",
    "oven",
    "toaster",
    "sink",
    "refrigerator",
    "book",
    "clock",
    "vase",
    "scissors",
    "teddy bear",
    "hair drier",
    "toothbrush",
)

def add_trackable_classes(apps, schema_editor):
    TrackableClass = apps.get_model('timeline', 'TrackableClass')

    for class_id, name in enumerate(DEFAULT_TRACKABLE_CLASSES):
        trackable_class = TrackableClass(name=name, class_id=class_id)
        trackable_class.save()

class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0006_alter_event_image_path'),
    ]

    operations = [
            migrations.RunPython(add_trackable_classes),
    ]
